// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Component(Props) {
  var text = Props.text;
  var style = Props.style;
  var func = Props.func;
  if (typeof style === "number") {
    if (style !== 0) {
      
    } else {
      
    }
  }
  Curry._1(func, undefined);
  return React.createElement(React.Fragment, undefined, text);
}

var make = Component;

exports.make = make;
/* react Not a pure module */
