// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function someFunction($$process, anotherSubFunction, content) {
  return Curry._1(anotherSubFunction, {
              content: Curry._1($$process, content)
            });
}

var x = "hello";

exports.someFunction = someFunction;
exports.x = x;
/* No side effect */
